version: '3.8'
services:
  backend:
    build:
      context: ./  # тут Dockerfile бекенду знаходиться у поточній директорії
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty
    depends_on:
      - db

  frontend:
    build:
      context: "C:/Users/volod/OneDrive/Desktop/work/shopfrontend/frontend"
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
